package tr.com.huseyinaydin.application.validation;

public interface BankingValidationCodes {

    String FIRST_NAME_REQUIRED           = "FIRST_NAME_REQUIRED";
    String FIRST_NAME_MAX_LENGTH         = "FIRST_NAME_MAX_LENGTH";
    String LAST_NAME_REQUIRED            = "LAST_NAME_REQUIRED";
    String LAST_NAME_MAX_LENGTH          = "LAST_NAME_MAX_LENGTH";
    String NATIONAL_ID_REQUIRED          = "NATIONAL_ID_REQUIRED";
    String NATIONAL_ID_INVALID           = "NATIONAL_ID_INVALID";
    String DATE_OF_BIRTH_REQUIRED        = "DATE_OF_BIRTH_REQUIRED";
    String MINIMUM_AGE_REQUIRED          = "MINIMUM_AGE_REQUIRED";
    String PHONE_REQUIRED                = "PHONE_REQUIRED";
    String PHONE_INVALID                 = "PHONE_INVALID";
    String EMAIL_REQUIRED                = "EMAIL_REQUIRED";
    String EMAIL_INVALID                 = "EMAIL_INVALID";
    String PASSWORD_REQUIRED             = "PASSWORD_REQUIRED";
    String PASSWORD_TOO_SHORT            = "PASSWORD_TOO_SHORT";
    String PASSWORD_NEEDS_UPPERCASE      = "PASSWORD_NEEDS_UPPERCASE";
    String PASSWORD_NEEDS_LOWERCASE      = "PASSWORD_NEEDS_LOWERCASE";
    String PASSWORD_NEEDS_DIGIT          = "PASSWORD_NEEDS_DIGIT";

    String COMPANY_NAME_REQUIRED         = "COMPANY_NAME_REQUIRED";
    String COMPANY_NAME_MAX_LENGTH       = "COMPANY_NAME_MAX_LENGTH";
    String TAX_NUMBER_REQUIRED           = "TAX_NUMBER_REQUIRED";
    String TAX_NUMBER_INVALID            = "TAX_NUMBER_INVALID";
    String AUTHORIZED_PERSON_REQUIRED    = "AUTHORIZED_PERSON_REQUIRED";

    String CUSTOMER_ID_REQUIRED          = "CUSTOMER_ID_REQUIRED";
    String CREDIT_TYPE_ID_REQUIRED       = "CREDIT_TYPE_ID_REQUIRED";
    String AMOUNT_REQUIRED               = "AMOUNT_REQUIRED";
    String AMOUNT_MUST_BE_POSITIVE       = "AMOUNT_MUST_BE_POSITIVE";
    String AMOUNT_EXCEEDS_MAX            = "AMOUNT_EXCEEDS_MAX";
    String TERM_OUT_OF_RANGE             = "TERM_OUT_OF_RANGE";

    String CREDIT_TYPE_NAME_REQUIRED     = "CREDIT_TYPE_NAME_REQUIRED";
    String CUSTOMER_TYPE_REQUIRED        = "CUSTOMER_TYPE_REQUIRED";
    String MIN_AMOUNT_REQUIRED           = "MIN_AMOUNT_REQUIRED";
    String MAX_AMOUNT_REQUIRED           = "MAX_AMOUNT_REQUIRED";
    String MIN_AMOUNT_MUST_BE_POSITIVE   = "MIN_AMOUNT_MUST_BE_POSITIVE";
    String MAX_AMOUNT_MUST_BE_POSITIVE   = "MAX_AMOUNT_MUST_BE_POSITIVE";
    String MIN_AMOUNT_EXCEEDS_MAX_AMOUNT = "MIN_AMOUNT_EXCEEDS_MAX_AMOUNT";
    String MIN_TERM_INVALID              = "MIN_TERM_INVALID";
    String MAX_TERM_INVALID              = "MAX_TERM_INVALID";
    String MIN_TERM_EXCEEDS_MAX_TERM     = "MIN_TERM_EXCEEDS_MAX_TERM";
    String INTEREST_RATE_REQUIRED        = "INTEREST_RATE_REQUIRED";
    String INTEREST_RATE_OUT_OF_RANGE    = "INTEREST_RATE_OUT_OF_RANGE";
}
